#!/bin/bash

# simple wrapper over casperjs script

search_url="$1"
default_mail=$2
free_sms_api_user=$3
free_sms_api_pass=$4
mail_title="leboncoin notifier"
base_dir="$(dirname $0)"

if [[ ! $2 ]]; then
    echo >&2 "Usage: $0 <leboncoin search url> <email> [free_sms_api_user] [free_sms_api_pass]"
    exit 1
fi

shopt -s nullglob

intrandfromrange() { echo $(( ( RANDOM % ($2 - $1 +1 ) ) + $1 )); }

# makes some randomness when used in crontab
if [[ ! -t 0 ]]; then
    sleep $(intrandfromrange 1 1200)
else
    verbose='-v'
fi

rm -f /tmp/lbc_[0-9a-fA-F]*_.png

cd "$base_dir"

# if there's some fresh links, the caspersjs script will create images matching /tmp/lbc_[0-9a-fA-F]*.png
casperjs leboncoin-alerter.js --url="$search_url" "$@"

for image in /tmp/lbc_[0-9a-fA-F]*_.png; do
    b64=$(awk -F_ '{print $2}' <<< "$image")
    url=$(base64 -d <<< "$b64")
    if [[ -s $image ]]; then
        echo "$url" |
            # send email with captured image + link
            mail $verbose -a "$image" -s "$mail_title" $default_mail
            # send sms with free SMS API if this argument is provided
            [[ $free_sms_api_pass ]] && curl $verbose "https://smsapi.free-mobile.fr/sendmsg?user=$free_sms_api_user&pass=$free_sms_api_pass&msg=check%20email%20for%20leboncoin%20alerter"
    fi
done
